{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.4.0-alpha01.aar",
          "url": "navigation-runtime-2.4.0-alpha01.aar",
          "size": 54794,
          "sha512": "636d896a3e443752af3ce9b6c81441d21e52aaceccd60095a3255cc946fb00d7bff6efad8bf8636050731746966b7f3eaae41204fea40d6849c63cda5a890b57",
          "sha256": "e46e6dff9189ab3bb67640506d392fe79d3f066b661d65a4846f4af1953c1daf",
          "sha1": "2ab8b9b47312a51649bb0e27ed2d698bed55bfd4",
          "md5": "858c8c632e657ca204c1ff88156f9528"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.4.0-alpha01.aar",
          "url": "navigation-runtime-2.4.0-alpha01.aar",
          "size": 54794,
          "sha512": "636d896a3e443752af3ce9b6c81441d21e52aaceccd60095a3255cc946fb00d7bff6efad8bf8636050731746966b7f3eaae41204fea40d6849c63cda5a890b57",
          "sha256": "e46e6dff9189ab3bb67640506d392fe79d3f066b661d65a4846f4af1953c1daf",
          "sha1": "2ab8b9b47312a51649bb0e27ed2d698bed55bfd4",
          "md5": "858c8c632e657ca204c1ff88156f9528"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-2.4.0-alpha01-sources.jar",
          "url": "navigation-runtime-2.4.0-alpha01-sources.jar",
          "size": 36171,
          "sha512": "04898c94fbf48cfbffb5177c251764b38cbe4675a6dcaf9d9b50a7f05e62deb42f5346ee34eed70e8be43e8559222094a1110a025e6cda170a6fee6bea425997",
          "sha256": "75a4e5ad95df511109e064e4b969dbfa721e0b54bff0744fdba7223b12688768",
          "sha1": "e8b770ee449b5bbd3da9fdce0bba6db82923d086",
          "md5": "3f83c2f01847123973648c7397e470ba"
        }
      ]
    }
  ]
}
