homepage: "https://www.imagemagick.org"
language: c++
primary_contact: "dirk@lemstra.org"
auto_ccs:
  - paul.l.kehrer@gmail.com
  - alex.gaynor@gmail.com
  - urban.warrior.fuzz@gmail.com
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/imagemagick/imagemagick'
