homepage: "https://github.com/google/flatbuffers"
language: c++
primary_contact: "wvo@google.com"
auto_ccs:
  - "Adam@adalogics.com"
  - "vglavnyy@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/google/flatbuffers'
