[package]
name = "vhost"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
assertions = { path = "../assertions" }
libc = "*"
net_util = { path = "../net_util" }
base = { path = "../base" }
virtio_sys = { path = "../virtio_sys" }
vm_memory = { path = "../vm_memory" }
