homepage: "https://github.com/assimp/assimp"
language: c++
primary_contact: "kim.kulling@googlemail.com"
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
main_repo: 'https://github.com/assimp/assimp.git'
