homepage: "https://github.com/open-source-parsers/jsoncpp/"
language: c++
primary_contact: "chenguopingdota@163.com"
auto_ccs:
 - "jophba@chromium.org"
sanitizers:
  - address
  - undefined
  - memory
main_repo: 'https://github.com/open-source-parsers/jsoncpp'
