branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Not really necessary, just to get a green badge on “master”
    - master
language: rust
dist: xenial
addons:
  apt:
    packages:
    - libclang-dev
env:
  - RUST_BACKTRACE=1 LLVM_CONFIG_PATH=llvm-3.8-config
script:
  - cargo test --verbose --all
