homepage: "https://github.com/pkg/sftp"
primary_contact: "nicola.murino@gmail.com"
auto_ccs:
  - "p.antoine@catenacyber.fr"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: 'https://github.com/pkg/sftp'
