{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.slice",
    "module": "slice-view",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "slice-view-1.1.0-alpha02.aar",
          "url": "slice-view-1.1.0-alpha02.aar",
          "size": 298895,
          "sha512": "fc1314f86d26fe8c9e1c56118600135e095bd706dfe60215596b76d4d96e32449e65c53922a2a2eb2d74768272360e85ee4b90d6eb527b8dbb186d09f4cea920",
          "sha256": "96d1b771c5d3510378ded3664d12f655a5e1b8d306dbede5208aa2cb4f61411b",
          "sha1": "44926163e495a7b9abe88b94810034ed26953432",
          "md5": "2886fff19a0cc4428d298247f954f7f0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.slice",
          "module": "slice-core",
          "version": {
            "requires": "1.1.0-alpha02"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "slice-view-1.1.0-alpha02.aar",
          "url": "slice-view-1.1.0-alpha02.aar",
          "size": 298895,
          "sha512": "fc1314f86d26fe8c9e1c56118600135e095bd706dfe60215596b76d4d96e32449e65c53922a2a2eb2d74768272360e85ee4b90d6eb527b8dbb186d09f4cea920",
          "sha256": "96d1b771c5d3510378ded3664d12f655a5e1b8d306dbede5208aa2cb4f61411b",
          "sha1": "44926163e495a7b9abe88b94810034ed26953432",
          "md5": "2886fff19a0cc4428d298247f954f7f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slice-view-1.1.0-alpha02-sources.jar",
          "url": "slice-view-1.1.0-alpha02-sources.jar",
          "size": 109655,
          "sha512": "04775727d19e8425dbfbe4d3d596c6fe9af97aadbeed899721a2d687d7d0039f1729f0242e5244bea92f9987d45476529a7e47ea33def92db3d0c0e3c6ab41c0",
          "sha256": "dc9766f8fb6e4d739a643da3f0451785fccfa8b1b3091034a255b5aaeabf4dbf",
          "sha1": "23f63578f6d109bf7cb816bd971fdae244e1beda",
          "md5": "483f46a3accf295a7409fcecaf8be7a1"
        }
      ]
    }
  ]
}
