{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recommendation",
    "module": "recommendation",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recommendation-1.1.0-alpha01.aar",
          "url": "recommendation-1.1.0-alpha01.aar",
          "size": 13387,
          "sha512": "6bfa985ab8c3330aac132b72d3a7cfc44aa51c0f0879a37521f499a40e0ef9e89cdd1b9d77c3f540982d36a63f7a1ddb0046f2405ec9ca31e6af83b9c040f720",
          "sha256": "c303eeb98cb3e38288107120a2ea50c36243315baffeb7dc4e826961eb5e9719",
          "sha1": "158c2d5b2979248cb30b4b06c0070aacc8c3a75f",
          "md5": "59797569bfb0d40ef7da6a6b42030c72"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recommendation-1.1.0-alpha01.aar",
          "url": "recommendation-1.1.0-alpha01.aar",
          "size": 13387,
          "sha512": "6bfa985ab8c3330aac132b72d3a7cfc44aa51c0f0879a37521f499a40e0ef9e89cdd1b9d77c3f540982d36a63f7a1ddb0046f2405ec9ca31e6af83b9c040f720",
          "sha256": "c303eeb98cb3e38288107120a2ea50c36243315baffeb7dc4e826961eb5e9719",
          "sha1": "158c2d5b2979248cb30b4b06c0070aacc8c3a75f",
          "md5": "59797569bfb0d40ef7da6a6b42030c72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recommendation-1.1.0-alpha01-sources.jar",
          "url": "recommendation-1.1.0-alpha01-sources.jar",
          "size": 11751,
          "sha512": "5c2b0fd9ef0400d7157b02a4190e2c37a10fea64a3db2ba9a7b908233c253e1124ddb23f2acbc04fe1db3f58e420c63795141baae835caca781ae8ad2f73dd98",
          "sha256": "529697db268529a51c3c8250c671441d37d806b1cd91434db54ba20c04f8d8e0",
          "sha1": "9e0dee3a88c622ad9957c780888d2954c9be541a",
          "md5": "394036952cbc8e7a59dc554d6dd1a77f"
        }
      ]
    }
  ]
}
