[package]
name = "vm_memory"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
cros_async = { path = "../cros_async" } # provided by ebuild
data_model = { path = "../data_model" } # provided by ebuild
libc = "*"
base = { path = "../base" } # provided by ebuild
bitflags = "1"

[workspace]
