homepage: "http://php.net/"
language: c++
primary_contact: "stas@php.net"
auto_ccs:
 - "smalyshev@gmail.com"
 - "nikita.ppv@gmail.com"
sanitizers:
 - address
 - undefined
 - memory
architectures:
 - x86_64
 - i386
main_repo: 'https://github.com/php/php-src.git'
