homepage: "https://www.zeek.org"
language: c++
primary_contact: "security@zeek.org"
auto_ccs:
  - "jsiwek@corelight.com"
  - "robin@corelight.com"
  - "johanna@corelight.com"
  - "tim@corelight.com"
  - "seth@corelight.com"
  - "justin@corelight.com"
  - "vern@corelight.com"
  - "vlad@es.net"
  - "dominik.charousset@corelight.com"
sanitizers:
  - address
main_repo: 'https://github.com/zeek/zeek'
