homepage: "www.grinninglizard.com/tinyxml2"
language: c++
primary_contact: "leethomason@gmail.com"
auto_ccs:
  - "pranjal.jumde@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/leethomason/tinyxml2'
