homepage: "https://www.crummy.com/software/BeautifulSoup/"
main_repo: "https://code.launchpad.net/~leonardr/beautifulsoup/bs4"
language: python
primary_contact: "leonard.richardson@gmail.com"
auto_ccs:
  - "jvoisin@google.com"
  - "ipudney@google.com"
  - "security@tidelift.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
