{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.viewpager2",
    "module": "viewpager2",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "viewpager2-1.1.0-alpha02.aar",
          "url": "viewpager2-1.1.0-alpha02.aar",
          "size": 66703,
          "sha512": "91d939c8678b69976639fc406087745d3152b54527e00bbb72710de58de6cc62edcaca764cf58c0a8e4de1fe6bfe561a4395873c4006e044e2041c2cadbe8035",
          "sha256": "23fc2576a1d7bed6da2d9fab8f2a516f14898ea7c1dcb717c579f26725b74922",
          "sha1": "034bec56c38cf80e26077c5eb03b05119bc5c6f7",
          "md5": "e252181f70792c41e08daa4e9e738eda"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewpager2-1.1.0-alpha02.aar",
          "url": "viewpager2-1.1.0-alpha02.aar",
          "size": 66703,
          "sha512": "91d939c8678b69976639fc406087745d3152b54527e00bbb72710de58de6cc62edcaca764cf58c0a8e4de1fe6bfe561a4395873c4006e044e2041c2cadbe8035",
          "sha256": "23fc2576a1d7bed6da2d9fab8f2a516f14898ea7c1dcb717c579f26725b74922",
          "sha1": "034bec56c38cf80e26077c5eb03b05119bc5c6f7",
          "md5": "e252181f70792c41e08daa4e9e738eda"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "viewpager2-1.1.0-alpha02-sources.jar",
          "url": "viewpager2-1.1.0-alpha02-sources.jar",
          "size": 39328,
          "sha512": "9332cf0e1bbe97ca06a640c27ad7b8c65a0cffaa0c4074abaa11adbca832e2c1220cb4fd4e1fa736bff96a1343651045b390f274a6182abb3577e76e583a51e6",
          "sha256": "bd9cd5ce12ec38a6b4593303675ab35c9a95273b28c51876f409a2dd4dcb3823",
          "sha1": "921826aed498ed0ebd4304290c9d7be5da573f73",
          "md5": "d1da2f3fd12199b88e3da5a73fc54b3d"
        }
      ]
    }
  ]
}
