{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.collection",
    "module": "collection-ktx",
    "version": "1.2.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "collection-ktx-1.2.0-alpha02.jar",
          "url": "collection-ktx-1.2.0-alpha02.jar",
          "size": 18892,
          "sha512": "5167228db87e34d3d87ec4ef1bdeb6a286b50198adc3f7f40727b1e63de37416520a208608be2dccd329b3d51285272680f4ef3630526ca8211ee9882bd29690",
          "sha256": "817c985cd523da40ebd9b600a421308fc30f11deb8c4c451de632f2f26258860",
          "sha1": "919f7397e7db86d9c054926c980d11acb1e4216f",
          "md5": "6e5517558089bb634db0cb8f6c233df1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "collection-ktx-1.2.0-alpha02.jar",
          "url": "collection-ktx-1.2.0-alpha02.jar",
          "size": 18892,
          "sha512": "5167228db87e34d3d87ec4ef1bdeb6a286b50198adc3f7f40727b1e63de37416520a208608be2dccd329b3d51285272680f4ef3630526ca8211ee9882bd29690",
          "sha256": "817c985cd523da40ebd9b600a421308fc30f11deb8c4c451de632f2f26258860",
          "sha1": "919f7397e7db86d9c054926c980d11acb1e4216f",
          "md5": "6e5517558089bb634db0cb8f6c233df1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "collection-ktx-1.2.0-alpha02-sources.jar",
          "url": "collection-ktx-1.2.0-alpha02-sources.jar",
          "size": 6005,
          "sha512": "7de8104057e72b4500bcd5fbe849a19f881c6a11acc3281b193574e790d0b7bde6b3aa2df4fbb3ef3ab251ba43e412770ea9995a7062e36fc34dc04a3e76195b",
          "sha256": "3e2ef9c8e1a8da244e56e1e4a7f6bc68fb1d0540a5ac626a4956e9ab98a45519",
          "sha1": "9ee182ad504e3aa9c1fa53602342409c265d2e8e",
          "md5": "b04f8fbb3052b48bd98d4d63e21d9b26"
        }
      ]
    }
  ]
}
