homepage: "http://libusb.info/"
language: c++
primary_contact: "christopher.a.dickens@gmail.com"
auto_ccs:
  - "hjelmn@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
main_repo: 'https://github.com/libusb/libusb'
