homepage: "http://svn.freebsd.org/base/head/sys/teken/"
language: c++
primary_contact: "ed@nuxi.nl"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - undefined
  - memory
  - dataflow
