homepage: "https://www.eprosima.com/"
language: c++
primary_contact: "miguelcompany@eprosima.com"
auto_ccs:
- "p.antoine@catenacyber.fr"
sanitizers:
- address
- undefined
main_repo: 'https://github.com/eProsima/Fast-DDS.git'
