language: rust

matrix:
  include:
    # MSRV
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: 1.13.0

      # 32-bit
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-gnu

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - staging
    - trying

notifications:
  email:
    on_success: never
