homepage: "https://github.com/rdkit/rdkit"
language: c++
primary_contact: "greg.landrum@gmail.com"
sanitizers:
  - address
  - undefined
  - memory
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/rdkit/rdkit.git'
