homepage: "https://www.tcpdump.org"
language: c++
primary_contact: "security@tcpdump.org"
auto_ccs :
  - "p.antoine@catenacyber.fr"
  - "infra.station@gmail.com"
  - "guy@alum.mit.edu"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - memory
  - undefined
  - dataflow
main_repo: 'https://github.com/the-tcpdump-group/libpcap.git'
