[package]
authors = ["The Rust Project Developers"]
name = "profiler_builtins"
version = "0.0.0"
edition = "2018"

[lib]
test = false
bench = false
doc = false

[dependencies]
core = { path = "../core" }
compiler_builtins = { version = "0.1.0", features = ['rustc-dep-of-std'] }

[build-dependencies]
cc = "1.0.1"
