{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media",
    "module": "media",
    "version": "1.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-1.3.0-beta01.aar",
          "url": "media-1.3.0-beta01.aar",
          "size": 328330,
          "sha512": "58feacf9e9e79b63ecfef85e3f71235f45cc23bc6789f72d050fad933da204de67194529dc8b22fb01f7faa86cb3426c8b54eb959863bc743cbc1ee97dd56a26",
          "sha256": "0431b3f07044656fc71ec4b611a1bb7aa9eb98d344d86d009c36ab4a9f707628",
          "sha1": "046406c8f9e76dc1d05ae4005dd583b587ecbb7b",
          "md5": "566904fba80aa1f8c57a7581665617b3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-1.3.0-beta01.aar",
          "url": "media-1.3.0-beta01.aar",
          "size": 328330,
          "sha512": "58feacf9e9e79b63ecfef85e3f71235f45cc23bc6789f72d050fad933da204de67194529dc8b22fb01f7faa86cb3426c8b54eb959863bc743cbc1ee97dd56a26",
          "sha256": "0431b3f07044656fc71ec4b611a1bb7aa9eb98d344d86d009c36ab4a9f707628",
          "sha1": "046406c8f9e76dc1d05ae4005dd583b587ecbb7b",
          "md5": "566904fba80aa1f8c57a7581665617b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media-1.3.0-beta01-sources.jar",
          "url": "media-1.3.0-beta01-sources.jar",
          "size": 140892,
          "sha512": "49d30db533ba2cd308b21b674dbce190df5e8b4cf6c3909fbaefc7c43978d14627d4e1eb0f671945c63fbdafa2ae6028c066e66a47e979a9491b8690c8972d4b",
          "sha256": "0340a9455022451af4d5df51e71f6010baed4b51635ff22cdcd88c1292639808",
          "sha1": "843837d3418132513d1542e5335c38b1d3013d98",
          "md5": "57c25568043b25f1844ff769141f4ec1"
        }
      ]
    }
  ]
}
