homepage: "https://github.com/PJK/libcbor"
language: c++
primary_contact: "me@pavelkalvoda.com"
auto_ccs:
  - alex.gaynor@gmail.com
fuzzing_engines:
  - afl
  - libfuzzer
  - honggfuzz
sanitizers:
  - address
  - undefined
  - memory
main_repo: 'https://github.com/PJK/libcbor'
