homepage: "https://github.com/zyantific/zydis"
language: c
primary_contact: "joel.hoener@gmail.com"
auto_ccs:
 - "flobernd90@gmail.com"
sanitizers:
 - address
 - memory
 - undefined
main_repo: 'https://github.com/zyantific/zydis.git'
