{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.documentfile",
    "module": "documentfile",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "documentfile-1.1.0-alpha01.aar",
          "url": "documentfile-1.1.0-alpha01.aar",
          "size": 12217,
          "sha512": "0fb8f19ae7935e4acfae6966c8108c3d0483bcade920cffe39096060431d7ab053771c37ae35343e9df8d570ca6e80e9ebab792811b0fadf7c28c105dfbb7ea2",
          "sha256": "57a9a5c9db39a734881c2568a0c33adfb55231bc28b3bf26a40dc53c5669c6c7",
          "sha1": "0ab7ada937a38cbe8a8b8d3626913d7e0c3f4891",
          "md5": "934e1ed3ed843348077d57f92e204975"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "documentfile-1.1.0-alpha01.aar",
          "url": "documentfile-1.1.0-alpha01.aar",
          "size": 12217,
          "sha512": "0fb8f19ae7935e4acfae6966c8108c3d0483bcade920cffe39096060431d7ab053771c37ae35343e9df8d570ca6e80e9ebab792811b0fadf7c28c105dfbb7ea2",
          "sha256": "57a9a5c9db39a734881c2568a0c33adfb55231bc28b3bf26a40dc53c5669c6c7",
          "sha1": "0ab7ada937a38cbe8a8b8d3626913d7e0c3f4891",
          "md5": "934e1ed3ed843348077d57f92e204975"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "documentfile-1.1.0-alpha01-sources.jar",
          "url": "documentfile-1.1.0-alpha01-sources.jar",
          "size": 11018,
          "sha512": "52135cc55a540b872739b6e2a69634025a308be3fa54c47ad62db20fd068c1c963c4198e3b27158160b35c77b15823afe55a9a40f9b0aed046803ca5cc4ba362",
          "sha256": "35963c13d0bdc0722b9585f1bc048372a43f57b1e9b7a894296f7813160dda2d",
          "sha1": "521cd68e6ef5140da8d5fe57087b48eccc68b27e",
          "md5": "ecd71186c6e45679a923cff0437c0182"
        }
      ]
    }
  ]
}
