homepage: "https://open62541.org/"
language: c++
primary_contact: "Stefan.Profanter@gmail.com"
auto_ccs:
 - "julius.pfrommer@gmail.com"
 - "chris_paul.iatrou@tu-dresden.de"
 - "ari.breitkreuz@gmail.com"
sanitizers:
- address
- undefined
- memory
main_repo: 'https://github.com/open62541/open62541.git'
