homepage: "https://www.torproject.org"
language: c++
primary_contact: "nima@torproject.org"
auto_ccs:
  - "nick.a.mathewson@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
sanitizers:
 - address
 - memory
 - undefined
main_repo: 'https://git.torproject.org/tor.git'
