homepage: "https://github.com/mozilla/bleach"
main_repo: "https://github.com/mozilla/bleach"
language: python
primary_contact: "gguthe@mozilla.com"
auto_ccs:
  - "jvoisin@google.com"
  - "ipudney@google.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
