{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation-experimental",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotation-experimental-1.2.0-alpha01.aar",
          "url": "annotation-experimental-1.2.0-alpha01.aar",
          "size": 24432,
          "sha512": "1aa5a104d14cfa90fb6485a3eb03d4b5b6950283295b5568b33ff5aed7d51d9fe610b8c9f5b795bde0c7a5d1c340b151d9aa93cac39a339170d31b031011bac4",
          "sha256": "aceb2e7b756669591a32022cc7a8e069fc88df978b7ce45fe9bfc6785f82c7cc",
          "sha1": "4c291b1e3bcc903bcac51c6607baf5cdd5f3b954",
          "md5": "d1709315886d4bf6d3eb4f6b9461fdb0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-experimental-1.2.0-alpha01.aar",
          "url": "annotation-experimental-1.2.0-alpha01.aar",
          "size": 24432,
          "sha512": "1aa5a104d14cfa90fb6485a3eb03d4b5b6950283295b5568b33ff5aed7d51d9fe610b8c9f5b795bde0c7a5d1c340b151d9aa93cac39a339170d31b031011bac4",
          "sha256": "aceb2e7b756669591a32022cc7a8e069fc88df978b7ce45fe9bfc6785f82c7cc",
          "sha1": "4c291b1e3bcc903bcac51c6607baf5cdd5f3b954",
          "md5": "d1709315886d4bf6d3eb4f6b9461fdb0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-experimental-1.2.0-alpha01-sources.jar",
          "url": "annotation-experimental-1.2.0-alpha01-sources.jar",
          "size": 5310,
          "sha512": "24d5b9245f60fc2b8b321e49743b4196dec130e42a83ca6a880353f78070d1772e64a3baae6cfef73f3e5616c803c7461eeb4833c4f9b48f56536c113fcfbe99",
          "sha256": "7ea8c98ebd649ee4c0a74b19e1e81ac5f4469be5a12555f288083f1efd4f29d9",
          "sha1": "238eb640abf1ca6c952c7cd2e9423fe7f715713f",
          "md5": "05d975aadee90454e8e41c039e3895ed"
        }
      ]
    }
  ]
}
