homepage: https://cgit.kde.org/kimageformats.git/
language: c++
primary_contact: tsdgeos@gmail.com
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://invent.kde.org/frameworks/kimageformats.git'
