{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-animation",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-animation-1.0.0-alpha03.aar",
          "url": "core-animation-1.0.0-alpha03.aar",
          "size": 126952,
          "sha512": "215f242f52bceffdc479982c1203b9586a5fd742003b4411ee85357b67622bbcee5c18195bb46bdab8b47729977642a68ccaf21059d7ef36f5fc12c17a3c2d05",
          "sha256": "f4d7bf003bcfa443d559a57faea9eee974afd3dffbc05dd281f48f3bac981666",
          "sha1": "c7615d1fc1d74b1cf8ab6244180fad7c4c7dfea3",
          "md5": "7d6678f24dc64ee77dbe89a82aa39c3e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-animation-1.0.0-alpha03.aar",
          "url": "core-animation-1.0.0-alpha03.aar",
          "size": 126952,
          "sha512": "215f242f52bceffdc479982c1203b9586a5fd742003b4411ee85357b67622bbcee5c18195bb46bdab8b47729977642a68ccaf21059d7ef36f5fc12c17a3c2d05",
          "sha256": "f4d7bf003bcfa443d559a57faea9eee974afd3dffbc05dd281f48f3bac981666",
          "sha1": "c7615d1fc1d74b1cf8ab6244180fad7c4c7dfea3",
          "md5": "7d6678f24dc64ee77dbe89a82aa39c3e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-animation-1.0.0-alpha03-sources.jar",
          "url": "core-animation-1.0.0-alpha03-sources.jar",
          "size": 116677,
          "sha512": "c0c05ec50eb9599421558c35d6260e91c69f1026bf5b1dc2d9f0fa5387515ce73a0a12f6038147798325eda4fb43bab5fb9fc9027801557539dc5d0dc4172c28",
          "sha256": "1f241a64bc2211fcc9d6bb7a18624f84bc15bc29aa0eae71cdefeb704c7dba85",
          "sha1": "8ad03661be600fe8d9c08d00f57a9c6782b61ef1",
          "md5": "65fbb7c7fd44755a9f4ed4a3761eb5ee"
        }
      ]
    }
  ]
}
