homepage: "https://github.com/liblouis/liblouis"
main_repo: "https://github.com/liblouis/liblouis"
language: c
primary_contact: "christian.egli@sbs.ch"
auto_ccs:
  - "Adam@adalogics.com"
sanitizers:
  - address
  - undefined
  - memory
