homepage: "https://github.com/nats-io/nats-server"
primary_contact: "security@nats.io"
auto_ccs :
  - "adam@adalogics.com"
  - "mh@synadia.com"
  - "wally@synadia.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: 'https://github.com/nats-io/nats-server'
