homepage: "https://github.com/DaveGamble/cJSON"
language: c++
primary_contact: "max@maxbruckner.de"
auto_ccs:
  - "randy440088@gmail.com"
  - "wp_scut@163.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - undefined
  - memory
  - dataflow
main_repo: 'https://github.com/DaveGamble/cJSON.git'
