homepage: "https://github.com/grpc-ecosystem/grpc-gateway"
primary_contact: "grpc-gateway-maintainers@googlegroups.com"
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: 'https://github.com/grpc-ecosystem/grpc-gateway'
