[package]
name = "vm_control"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[features]
gdb = ["gdbstub_arch"]

[dependencies]
base = { path = "../base" }
data_model = { path = "../data_model" }
gdbstub_arch = { version = "0.1.0", optional = true }
hypervisor = { path = "../hypervisor" }
libc = "*"
resources = { path = "../resources" }
rutabaga_gfx = { path = "../rutabaga_gfx"}
serde = { version = "1", features = [ "derive" ] }
serde_json = "*"
sync = { path = "../sync" }
vm_memory = { path = "../vm_memory" }
