#!/bin/bash

# Copyright (C) 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# launcher script for cat-tradefed harness
# can be used from an Android build environment, or a standalone cat zip

checkFile() {
    if [ ! -f "$1" ]; then
        echo "Unable to locate $1"
        exit
    fi;
}

checkPath() {
    if ! type -P $1 &> /dev/null; then
        echo "Unable to find $1 in path."
        exit
    fi;
}

checkPath adb
checkPath java

# check debug flag and set up remote debugging
if [ -n "${TF_DEBUG}" ]; then
  if [ -z "${TF_DEBUG_PORT}" ]; then
    TF_DEBUG_PORT=10088
  fi
  RDBG_FLAG=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=${TF_DEBUG_PORT}
fi

# get OS
HOST=`uname`
if [ "$HOST" == "Linux" ]; then
    OS="linux-x86"
elif [ "$HOST" == "Darwin" ]; then
    OS="darwin-x86"
else
    echo "Unrecognized OS"
    exit
fi

# check if in Android build env
if [ ! -z "${ANDROID_BUILD_TOP}" ]; then
    if [ ! -z "${ANDROID_HOST_OUT}" ]; then
      CATBOX_ROOT=${ANDROID_HOST_OUT}/catbox
    else
      CATBOX_ROOT=${ANDROID_BUILD_TOP}/${OUT_DIR:-out}/host/${OS}/catbox
    fi
    if [ ! -d ${CATBOX_ROOT} ]; then
        echo "Could not find $CATBOX_ROOT in Android build environment. Try 'make catbox'"
        exit
    fi;
fi;

if [ -z ${CATBOX_ROOT} ]; then
    # assume we're in an extracted cat install
    CATBOX_ROOT="$(dirname $0)/../.."
fi;

JAR_DIR=${CATBOX_ROOT}/android-catbox/tools
JARS="tradefed
  loganalysis
  compatibility-host-util
  catbox-tradefed
  catbox-tradefed-tests
  catbox-report-lib"

for JAR in $JARS; do
    checkFile ${JAR_DIR}/${JAR}.jar
    JAR_PATH=${JAR_PATH}:${JAR_DIR}/${JAR}.jar
done

OPTIONAL_JARS="
  google-tradefed
  google-tradefed-tests
  google-tf-prod-tests"

for JAR in $OPTIONAL_JARS; do
    if [ -f "$JAR_DIR/$JAR.jar" ]; then
        JAR_PATH=${JAR_PATH}:${JAR_DIR}/${JAR}.jar
    fi;
done

# load any shared libraries for host-side executables
LIB_DIR=${CATBOX_ROOT}/android-catbox/lib
if [ "$HOST" == "Linux" ]; then
    LD_LIBRARY_PATH=${LIB_DIR}:${LIB_DIR}64:${LD_LIBRARY_PATH}
    export LD_LIBRARY_PATH
elif [ "$HOST" == "Darwin" ]; then
    DYLD_LIBRARY_PATH=${LIB_DIR}:${LIB_DIR}64:${DYLD_LIBRARY_PATH}
    export DYLD_LIBRARY_PATH
fi

# include any host-side test jars
for j in ${CATBOX_ROOT}/android-catbox/testcases/*.jar; do
    JAR_PATH=${JAR_PATH}:$j
done

if [ "$HOST" == "Darwin" ]; then
    local_tmp_dir="${ANDROID_HOST_OUT}/tmp"
    if [ ! -f "${local_tmp_dir}" ]; then
        mkdir -p "${local_tmp_dir}"
    fi
    java_tmp_dir_opt="-Djava.io.tmpdir=${local_tmp_dir}"
fi

java $RDBG_FLAG -cp ${JAR_PATH} -DCATBOX_ROOT=${CATBOX_ROOT} ${java_tmp_dir_opt} com.android.compatibility.common.tradefed.command.CompatibilityConsole "$@"
