environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    VERSION: 1.31.0
  - TARGET: i686-pc-windows-msvc
    VERSION: 1.31.0
  - TARGET: i686-pc-windows-gnu
    VERSION: 1.31.0
  - TARGET: x86_64-pc-windows-msvc
    VERSION: beta
  - TARGET: i686-pc-windows-msvc
    VERSION: beta
  - TARGET: i686-pc-windows-gnu
    VERSION: beta
  - TARGET: x86_64-pc-windows-msvc
    VERSION: nightly
  - TARGET: i686-pc-windows-msvc
    VERSION: nightly
  - TARGET: i686-pc-windows-gnu
    VERSION: nightly
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:VERSION}-${env:TARGET}.exe"
  - rust-%VERSION%-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --verbose
