name: Infra tests
on:
  pull_request:
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - run: |  # Needed for git diff to work.
          git fetch origin master --depth 1
          git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/master

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo env "PATH=$PATH" python -m pip install --upgrade pip
          sudo env "PATH=$PATH" pip install -r infra/ci/requirements.txt
          sudo env "PATH=$PATH" pip install -r infra/build/functions/requirements.txt

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '298.0.0'
      - run: |
          sudo env "PATH=$PATH" gcloud components install beta cloud-datastore-emulator

      - name: Run infra tests
        run: sudo env "PATH=$PATH" INTEGRATION_TESTS=1 python infra/presubmit.py infra-tests -p
