{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.interpolator",
    "module": "interpolator",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "interpolator-1.1.0-alpha01.aar",
          "url": "interpolator-1.1.0-alpha01.aar",
          "size": 8696,
          "sha512": "481b23dbedb79c05b934697abe210685c68a512a3bb8a7b77c719d2380d05c11810d69b553fc35f451822f40fe21f1fa33e00225db118329a61869b203751e42",
          "sha256": "f8f0c82c9aa787e0700f41ae9a353c0485aae594abe42d5d927ff98cf2262989",
          "sha1": "2693a91a1edac3e7abac3969796ad6c735897dc4",
          "md5": "d015845bb77ee307ddbdb5421e1f3902"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "interpolator-1.1.0-alpha01.aar",
          "url": "interpolator-1.1.0-alpha01.aar",
          "size": 8696,
          "sha512": "481b23dbedb79c05b934697abe210685c68a512a3bb8a7b77c719d2380d05c11810d69b553fc35f451822f40fe21f1fa33e00225db118329a61869b203751e42",
          "sha256": "f8f0c82c9aa787e0700f41ae9a353c0485aae594abe42d5d927ff98cf2262989",
          "sha1": "2693a91a1edac3e7abac3969796ad6c735897dc4",
          "md5": "d015845bb77ee307ddbdb5421e1f3902"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "interpolator-1.1.0-alpha01-sources.jar",
          "url": "interpolator-1.1.0-alpha01-sources.jar",
          "size": 6822,
          "sha512": "0bb7f6e999ad3f79ab6379b77ec8bf5f94013805109acafa4f2d5b2bed336f4a328986415686b274cfb6999cd93d6a5a3cf9da216e3edcae8bf31913c396828d",
          "sha256": "b424610869ff191adbc3fd5a3f978accd3de9aa4464032dd99b0f57eb8248a83",
          "sha1": "87c4b919f0886d09bd85d4626cadc9e08ef160af",
          "md5": "69943d660297c81234b76ece84a5db73"
        }
      ]
    }
  ]
}
