homepage: "https://github.com/richgel999/miniz"
language: c
primary_contact: "martin@urbackup.org"
auto_ccs:
  - "randy440088@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - undefined
  - memory
  - dataflow
main_repo: 'https://github.com/richgel999/miniz.git'
