homepage: "https://gitlab.isc.org/isc-projects/bind9"
language: c
primary_contact: "bind9-dev@isc.org"
auto_ccs:
  - "artem@isc.org"
  - "dfronza@isc.org"
  - "each@isc.org"
  - "marka@isc.org"
  - "matthijs@isc.org"
  - "michal@isc.org"
  - "mnowak@isc.org"
  - "ondrej@isc.org"
  - "pspacek@isc.org"
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
main_repo: 'https://gitlab.isc.org/isc-projects/bind9.git'
