homepage: "https://usbguard.github.io/"
language: c++
primary_contact: "rsroka@redhat.com"
sanitizers:
 - address
 - undefined
 - memory
auto_ccs:
 - "alakatos@redhat.com"
 - "allenwebb@google.com"
 - "zfridric@redhat.com"
main_repo: "https://github.com/USBGuard/usbguard"
