{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-alpha01.aar",
          "url": "lifecycle-livedata-core-2.4.0-alpha01.aar",
          "size": 9428,
          "sha512": "a73df89c3ea159ca501aac9ee7e404cf3046bb1bc53e6c196113d3134a612586f4006d1fd1fa6114b0416a217330aaf463c5158276989439891024192c732023",
          "sha256": "259ca62fbd20e68a1ffe0bbf5f89f0dd10f9562263de913d2df8c0ec5ddb5408",
          "sha1": "b75c66ab868c8af4eb02b56859a15bc0943f3553",
          "md5": "2c8fdc4c396dd404dec8daff7d809c1a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-alpha01.aar",
          "url": "lifecycle-livedata-core-2.4.0-alpha01.aar",
          "size": 9428,
          "sha512": "a73df89c3ea159ca501aac9ee7e404cf3046bb1bc53e6c196113d3134a612586f4006d1fd1fa6114b0416a217330aaf463c5158276989439891024192c732023",
          "sha256": "259ca62fbd20e68a1ffe0bbf5f89f0dd10f9562263de913d2df8c0ec5ddb5408",
          "sha1": "b75c66ab868c8af4eb02b56859a15bc0943f3553",
          "md5": "2c8fdc4c396dd404dec8daff7d809c1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-alpha01-sources.jar",
          "url": "lifecycle-livedata-core-2.4.0-alpha01-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}
