homepage: "https://github.com/pingcap/tidb"
primary_contact: "zhouqiang@pingcap.com"
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: 'https://github.com/pingcap/tidb'
