homepage: "https://github.com/CESNET/libyang"
main_repo: 'https://github.com/CESNET/libyang'
primary_contact: "mvasko@cesnet.cz"
language: c
auto_ccs:
  - "mv6606@gmail.com"
  - "david@adalogics.com"
  - "warband.times@gmail.com"
  - "juraj.vijtiuk@sartura.hr"
sanitizers:
  - address
  - memory
