homepage: "https://github.com/go-redis/redis"
main_repo: "https://github.com/go-redis/redis"
primary_contact: "vladimir.webdev@gmail.com"
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
