{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji",
    "module": "emoji-appcompat",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03.aar",
          "url": "emoji-appcompat-1.2.0-alpha03.aar",
          "size": 16387,
          "sha512": "7f048a038bd4a212aa608a75750875b5237e8432d3cd1119c84670672906fb6cf08bdd328ac1fa6620debb5a6336891e9c537955e25ce9c5798a3a64ca482199",
          "sha256": "181bcd6c39c1159a6874d1a31103620e2ae848168ac1bedbbdb739604cd7ffb1",
          "sha1": "81bd794568bdae45c6478a3573342c91f8976058",
          "md5": "543a24b82e027f9552b0913a93868414"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03.aar",
          "url": "emoji-appcompat-1.2.0-alpha03.aar",
          "size": 16387,
          "sha512": "7f048a038bd4a212aa608a75750875b5237e8432d3cd1119c84670672906fb6cf08bdd328ac1fa6620debb5a6336891e9c537955e25ce9c5798a3a64ca482199",
          "sha256": "181bcd6c39c1159a6874d1a31103620e2ae848168ac1bedbbdb739604cd7ffb1",
          "sha1": "81bd794568bdae45c6478a3573342c91f8976058",
          "md5": "543a24b82e027f9552b0913a93868414"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03-sources.jar",
          "url": "emoji-appcompat-1.2.0-alpha03-sources.jar",
          "size": 4355,
          "sha512": "05730b58fb8391f28050b8cc51cfb42fdfc6c888cbb70b642d1e8b11f82b15946b65f05350de21d4f222e58f2e2d97ed4e195facd843c06552b784e7c4edd8ec",
          "sha256": "8c37ea1aefdd5d8e36d6fd5d7535c6fdfadd02b61fa51c1e4178b0cec49e6de0",
          "sha1": "6100352f9c99794e5ec330e4e428e344a7b3a245",
          "md5": "d708308a2084b09201efe840d9541b78"
        }
      ]
    }
  ]
}
