{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.cardview",
    "module": "cardview",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cardview-1.1.0-alpha01.aar",
          "url": "cardview-1.1.0-alpha01.aar",
          "size": 24713,
          "sha512": "1699388fff2b32fba296535513321db96066ab3acd4c2c7d84aefaa163ad0ec423a4244eb454e5d0dfe42c640af573270aaa3af39c5a6d9db244a8a6024936f8",
          "sha256": "21ea73b634f0dc1238e378c280bdda0b42c8ac8dcef94139a36eb73bdd2e51f2",
          "sha1": "05cce9f33f627ffd093a61901becd8d1309f97fc",
          "md5": "23cfaf4ed57945398512ae8c6c50f96a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cardview-1.1.0-alpha01.aar",
          "url": "cardview-1.1.0-alpha01.aar",
          "size": 24713,
          "sha512": "1699388fff2b32fba296535513321db96066ab3acd4c2c7d84aefaa163ad0ec423a4244eb454e5d0dfe42c640af573270aaa3af39c5a6d9db244a8a6024936f8",
          "sha256": "21ea73b634f0dc1238e378c280bdda0b42c8ac8dcef94139a36eb73bdd2e51f2",
          "sha1": "05cce9f33f627ffd093a61901becd8d1309f97fc",
          "md5": "23cfaf4ed57945398512ae8c6c50f96a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cardview-1.1.0-alpha01-sources.jar",
          "url": "cardview-1.1.0-alpha01-sources.jar",
          "size": 16510,
          "sha512": "10f4f42e55922d01073e5b8ecfbaf70847e8662a8e214b49e468d5cf0156faf389a3b933969f51c4d62d4de2faf00c4826c492aaaeee9c54f0af205bdb217b18",
          "sha256": "1e63af91477f0f738c4e1b72a63e52c09737fca4ec91190645b3ace6787e0da2",
          "sha1": "a2f300361bb55705c74987c26471ed63aec851a7",
          "md5": "791bb9de8f4314c718e5218a05230b3c"
        }
      ]
    }
  ]
}
