{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.slice",
    "module": "slice-core",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "slice-core-1.1.0-alpha02.aar",
          "url": "slice-core-1.1.0-alpha02.aar",
          "size": 179385,
          "sha512": "9099724515e0222cbc5d4d7439b50f29ce79f20bdf674124473dee0b810fc94d4767300c9af7534d79d06745a69374e65681ae2561b95eed98141588a472c374",
          "sha256": "94952416e418014a176997cda5d216e869928907df31d8e7670917570aa25220",
          "sha1": "cfbaee84d85ab33b69a96da7037cba1289d8ca38",
          "md5": "deafbc5f14bc68d8634541c8ce25b55d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "slice-core-1.1.0-alpha02.aar",
          "url": "slice-core-1.1.0-alpha02.aar",
          "size": 179385,
          "sha512": "9099724515e0222cbc5d4d7439b50f29ce79f20bdf674124473dee0b810fc94d4767300c9af7534d79d06745a69374e65681ae2561b95eed98141588a472c374",
          "sha256": "94952416e418014a176997cda5d216e869928907df31d8e7670917570aa25220",
          "sha1": "cfbaee84d85ab33b69a96da7037cba1289d8ca38",
          "md5": "deafbc5f14bc68d8634541c8ce25b55d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slice-core-1.1.0-alpha02-sources.jar",
          "url": "slice-core-1.1.0-alpha02-sources.jar",
          "size": 53265,
          "sha512": "24922b355796f79879a2ffb8481b48df230b6eef5d38f03a360de33b37fb722c2f61bf4a35b466432a59c08dd80d991cb4e8e9114fe3f3a3c359ef26c8fffc1b",
          "sha256": "c0d5dd1529e0ac5300944d94fb1a3d645865d1005162720ae70494ca75bc76af",
          "sha1": "b8b42b9822aba99d7aa2b8701ff269447ee126bd",
          "md5": "8a81f4d81d71fde520a8d3d775527fe4"
        }
      ]
    }
  ]
}
