homepage: "https://python.org/"
language: c++
primary_contact: "guidovranken@gmail.com"
auto_ccs:
 - "gps@google.com"
 - "alex.gaynor@gmail.com"
 - "ammar@ammaraskar.com"
fuzzing_engines:
  - libfuzzer
  - honggfuzz
sanitizers:
 - address
 - undefined
