homepage: "https://github.com/miekg/dns"
primary_contact: "miek@miek.nl"
auto_ccs:
  - "me+google@tomthorogood.co.uk"
  - "p.antoine@catenacyber.fr"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/miekg/dns"
