homepage: "https://www.libreoffice.org/"
language: c++
primary_contact: "caolanm@redhat.com"
auto_ccs:
  - "officesecurity@lists.freedesktop.org"
  - "damjan.jov@gmail.com"
  - "noelgrandin@gmail.com"
  - "sbergman@redhat.com"
main_repo: 'https://git.libreoffice.org/core'
