{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.4.0-alpha01.aar",
          "url": "lifecycle-livedata-2.4.0-alpha01.aar",
          "size": 11211,
          "sha512": "4d34fe45520f3c0c767e8020dc644dc483288eb445ba787715227a06923ad4bb293b377f1c9d095902cc3126d6087195c217cf05f0e2e19236de0c12fa690b35",
          "sha256": "a1ecb7d00ca23e62a845841d549cec2db1220045ccb759fd48adb1880cd84cff",
          "sha1": "562abc8bca7c4c97ad34a90633d5714b98e00cea",
          "md5": "b67b3209232c79a93ad38713029d992b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.4.0-alpha01.aar",
          "url": "lifecycle-livedata-2.4.0-alpha01.aar",
          "size": 11211,
          "sha512": "4d34fe45520f3c0c767e8020dc644dc483288eb445ba787715227a06923ad4bb293b377f1c9d095902cc3126d6087195c217cf05f0e2e19236de0c12fa690b35",
          "sha256": "a1ecb7d00ca23e62a845841d549cec2db1220045ccb759fd48adb1880cd84cff",
          "sha1": "562abc8bca7c4c97ad34a90633d5714b98e00cea",
          "md5": "b67b3209232c79a93ad38713029d992b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.4.0-alpha01-sources.jar",
          "url": "lifecycle-livedata-2.4.0-alpha01-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
