{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-runtime",
    "version": "3.0.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.0.0-beta01"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.0.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.0.0-beta01.aar",
          "url": "paging-runtime-3.0.0-beta01.aar",
          "size": 67928,
          "sha512": "2c3e0ab7c5ce1cf2334c17e4338a2be8e6bfb40eb030a8efa5c35614df9a4333d86f364f36c33dd91da80edc9ac9c1f88909cf6a563ee32fe470b482e9106480",
          "sha256": "4c2737872db8edb53bc1df442c77fecd8e9c258e0487d61aa2c9a49fd4aa3dc7",
          "sha1": "f0ddc07dd13693ddd621341141d81b0c6dde294c",
          "md5": "03c4fb447d8a9f730304e958261a3a38"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.0.0-beta01"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.0.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.0.0-beta01.aar",
          "url": "paging-runtime-3.0.0-beta01.aar",
          "size": 67928,
          "sha512": "2c3e0ab7c5ce1cf2334c17e4338a2be8e6bfb40eb030a8efa5c35614df9a4333d86f364f36c33dd91da80edc9ac9c1f88909cf6a563ee32fe470b482e9106480",
          "sha256": "4c2737872db8edb53bc1df442c77fecd8e9c258e0487d61aa2c9a49fd4aa3dc7",
          "sha1": "f0ddc07dd13693ddd621341141d81b0c6dde294c",
          "md5": "03c4fb447d8a9f730304e958261a3a38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-runtime-3.0.0-beta01-sources.jar",
          "url": "paging-runtime-3.0.0-beta01-sources.jar",
          "size": 29173,
          "sha512": "91311b93739d9e490a30cb879e892fe31628c464e6861ea7987eb33233b9d15fc31e4fa900d6adaca383231ece01903b0156b61c1e7b8f8fb0094bcfcd0f77fe",
          "sha256": "6a8220c2d474961d6f470e718873d2ebb9d0fd0ee42ea5363a0e7f02cc5c347c",
          "sha1": "9451c728f4a177d3b700beff466b6d0ecea678c1",
          "md5": "8e3d3b34782364f36989642d2dc817d9"
        }
      ]
    }
  ]
}
