{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing",
    "version": "2.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.3.0-beta02.jar",
          "url": "room-compiler-processing-2.3.0-beta02.jar",
          "size": 582567,
          "sha512": "ecf985d98fc427adb666add55e132f274735519dd2b8c010a4a77f8481960aba67fb09a38cb738243515f3f49983b5a94be925f01602bd81559ceb93c19ca8ce",
          "sha256": "8a5f2087b7ec93fc4cad5e0e0335379e5231f2f8844ea422898ac91236f3077e",
          "sha1": "29198bc4df36b0e7ca24259120d111f4073d3051",
          "md5": "24311b871eb43346646da12c0861c6c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.4.30-1.0.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.3.0-beta02.jar",
          "url": "room-compiler-processing-2.3.0-beta02.jar",
          "size": 582567,
          "sha512": "ecf985d98fc427adb666add55e132f274735519dd2b8c010a4a77f8481960aba67fb09a38cb738243515f3f49983b5a94be925f01602bd81559ceb93c19ca8ce",
          "sha256": "8a5f2087b7ec93fc4cad5e0e0335379e5231f2f8844ea422898ac91236f3077e",
          "sha1": "29198bc4df36b0e7ca24259120d111f4073d3051",
          "md5": "24311b871eb43346646da12c0861c6c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-processing-2.3.0-beta02-sources.jar",
          "url": "room-compiler-processing-2.3.0-beta02-sources.jar",
          "size": 123584,
          "sha512": "b2b4569b07f151c6926ea8a8099035e2acbb7fd126ade0b8aeab661a2e75c485c46873f64166edcd6a6607d7542524737a0d540ec4ad1b53bb1eb977dd552724",
          "sha256": "330f8209167bd1a254cf727efe50bea5764938c0b914b78c3364eeee3b5c344e",
          "sha1": "b64912791b24481f4ffc71faf58c8c0e92a4de37",
          "md5": "d5aa2195bb17d6e95744cc7fbd3a3010"
        }
      ]
    }
  ]
}
