language: c
dist: focal

matrix:
  include:
    - compiler: gcc
      env: CC=gcc
    - compiler: clang
      env: CC=clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzstd-dev zstd
  - sudo apt-get install -qq liblzma-dev
  - sudo apt-get install -qq zlib1g-dev
  - sudo apt-get install -qq xsltproc docbook-xsl
  - sudo apt-get install -qq cython
  - sudo apt-get install -qq linux-headers-generic

before_script:
  - unset PYTHON_CFLAGS # hack to broken travis setup
  - export KDIR="$(find  /lib/modules/* -maxdepth  1 -name build | sort -n --reverse | head -1)"

script:
  - ./autogen.sh c --without-openssl && make -j
  - make -j check

notifications:
  irc:
    channels:
      - "irc.freenode.org#kmod"
    template:
      - "%{commit}: %{author} - %{message}"
