{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-runtime",
    "version": "2.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0-beta02"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.3.0-beta02.aar",
          "url": "room-runtime-2.3.0-beta02.aar",
          "size": 134608,
          "sha512": "4d4e8cfa4754be253506585b98691d89c04de3d8e4d9de4a6c816f51607763e6f0c7d6431447d599931cbe0124a09319a9ee83b8cdb5ef793c199e04ac91d504",
          "sha256": "cc7fa163f01b39a7a5ed6a42c2ffafd74fab2f9bb5dda187298d8189512803ea",
          "sha1": "289a6b9a657aaed88f284b45e91c87626d544cdb",
          "md5": "255e76ffe21647420b1cac3b52856d0d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0-beta02"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.3.0-beta02.aar",
          "url": "room-runtime-2.3.0-beta02.aar",
          "size": 134608,
          "sha512": "4d4e8cfa4754be253506585b98691d89c04de3d8e4d9de4a6c816f51607763e6f0c7d6431447d599931cbe0124a09319a9ee83b8cdb5ef793c199e04ac91d504",
          "sha256": "cc7fa163f01b39a7a5ed6a42c2ffafd74fab2f9bb5dda187298d8189512803ea",
          "sha1": "289a6b9a657aaed88f284b45e91c87626d544cdb",
          "md5": "255e76ffe21647420b1cac3b52856d0d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-runtime-2.3.0-beta02-sources.jar",
          "url": "room-runtime-2.3.0-beta02-sources.jar",
          "size": 91094,
          "sha512": "4ff9af8dad39072d863da4a2a4df59583bd8947516936f4dfa0b768b93f60695895733b0ca294f3cfd1bb23f7f862fce118ffcda1a6ba7a04198b7d20ff75d86",
          "sha256": "c1f15fa068c7bf7158c76c3060a4e6c0c0c62c1a9ddded075017dd10a7939e36",
          "sha1": "f538a217836db2674d9d096b1932f42d62d0bffe",
          "md5": "170e3458a087d5fb304dd66148a18839"
        }
      ]
    }
  ]
}
