homepage: "https://github.com/protobuf-c/protobuf-c"
language: c
primary_contact: "guidovranken@gmail.com"
auto_ccs:
  - "ilya.lipnitskiy@gmail.com"
sanitizers:
 - address
 - memory
architectures:
 - x86_64
 - i386
main_repo: 'https://github.com/protobuf-c/protobuf-c.git'
coverage_extra_args: -ignore-filename-regex=.*/protobuf-install/.*
