# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tools/asuite/atest/tf_proto/metric_measurement.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tools/asuite/atest/tf_proto/metric_measurement.proto',
  package='tradefed.metric',
  syntax='proto3',
  serialized_options=_b('\n\"com.android.tradefed.metrics.protoB\021MetricMeasurement'),
  serialized_pb=_b('\n4tools/asuite/atest/tf_proto/metric_measurement.proto\x12\x0ftradefed.metric\"\x8f\x02\n\x0cMeasurements\x12\x17\n\rsingle_string\x18\x01 \x01(\tH\x00\x12\x14\n\nsingle_int\x18\x02 \x01(\x03H\x00\x12\x17\n\rsingle_double\x18\x03 \x01(\x01H\x00\x12\x36\n\rstring_values\x18\x04 \x01(\x0b\x32\x1d.tradefed.metric.StringValuesH\x00\x12\x38\n\x0enumeric_values\x18\x05 \x01(\x0b\x32\x1e.tradefed.metric.NumericValuesH\x00\x12\x36\n\rdouble_values\x18\x06 \x01(\x0b\x32\x1d.tradefed.metric.DoubleValuesH\x00\x42\r\n\x0bmeasurement\"$\n\x0cStringValues\x12\x14\n\x0cstring_value\x18\x01 \x03(\t\"&\n\rNumericValues\x12\x15\n\rnumeric_value\x18\x01 \x03(\x03\"$\n\x0c\x44oubleValues\x12\x14\n\x0c\x64ouble_value\x18\x01 \x03(\x01\"\xa8\x01\n\x06Metric\x12\x33\n\x0cmeasurements\x18\x01 \x01(\x0b\x32\x1d.tradefed.metric.Measurements\x12\x0c\n\x04unit\x18\x02 \x01(\t\x12\x32\n\tdirection\x18\x03 \x01(\x0e\x32\x1f.tradefed.metric.Directionality\x12\'\n\x04type\x18\x04 \x01(\x0e\x32\x19.tradefed.metric.DataType*c\n\x0e\x44irectionality\x12\x1e\n\x1a\x44IRECTIONALITY_UNSPECIFIED\x10\x00\x12\r\n\tUP_BETTER\x10\x01\x12\x0f\n\x0b\x44OWN_BETTER\x10\x02\x12\x11\n\rCLOSER_BETTER\x10\x03*\"\n\x08\x44\x61taType\x12\x07\n\x03RAW\x10\x00\x12\r\n\tPROCESSED\x10\x01\x42\x37\n\"com.android.tradefed.metrics.protoB\x11MetricMeasurementb\x06proto3')
)

_DIRECTIONALITY = _descriptor.EnumDescriptor(
  name='Directionality',
  full_name='tradefed.metric.Directionality',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIRECTIONALITY_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UP_BETTER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWN_BETTER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSER_BETTER', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=634,
  serialized_end=733,
)
_sym_db.RegisterEnumDescriptor(_DIRECTIONALITY)

Directionality = enum_type_wrapper.EnumTypeWrapper(_DIRECTIONALITY)
_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='tradefed.metric.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RAW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=735,
  serialized_end=769,
)
_sym_db.RegisterEnumDescriptor(_DATATYPE)

DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
DIRECTIONALITY_UNSPECIFIED = 0
UP_BETTER = 1
DOWN_BETTER = 2
CLOSER_BETTER = 3
RAW = 0
PROCESSED = 1



_MEASUREMENTS = _descriptor.Descriptor(
  name='Measurements',
  full_name='tradefed.metric.Measurements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='single_string', full_name='tradefed.metric.Measurements.single_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='single_int', full_name='tradefed.metric.Measurements.single_int', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='single_double', full_name='tradefed.metric.Measurements.single_double', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_values', full_name='tradefed.metric.Measurements.string_values', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numeric_values', full_name='tradefed.metric.Measurements.numeric_values', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='double_values', full_name='tradefed.metric.Measurements.double_values', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='measurement', full_name='tradefed.metric.Measurements.measurement',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=74,
  serialized_end=345,
)


_STRINGVALUES = _descriptor.Descriptor(
  name='StringValues',
  full_name='tradefed.metric.StringValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_value', full_name='tradefed.metric.StringValues.string_value', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=383,
)


_NUMERICVALUES = _descriptor.Descriptor(
  name='NumericValues',
  full_name='tradefed.metric.NumericValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numeric_value', full_name='tradefed.metric.NumericValues.numeric_value', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=423,
)


_DOUBLEVALUES = _descriptor.Descriptor(
  name='DoubleValues',
  full_name='tradefed.metric.DoubleValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='double_value', full_name='tradefed.metric.DoubleValues.double_value', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=461,
)


_METRIC = _descriptor.Descriptor(
  name='Metric',
  full_name='tradefed.metric.Metric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='measurements', full_name='tradefed.metric.Metric.measurements', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='tradefed.metric.Metric.unit', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='tradefed.metric.Metric.direction', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='tradefed.metric.Metric.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=632,
)

_MEASUREMENTS.fields_by_name['string_values'].message_type = _STRINGVALUES
_MEASUREMENTS.fields_by_name['numeric_values'].message_type = _NUMERICVALUES
_MEASUREMENTS.fields_by_name['double_values'].message_type = _DOUBLEVALUES
_MEASUREMENTS.oneofs_by_name['measurement'].fields.append(
  _MEASUREMENTS.fields_by_name['single_string'])
_MEASUREMENTS.fields_by_name['single_string'].containing_oneof = _MEASUREMENTS.oneofs_by_name['measurement']
_MEASUREMENTS.oneofs_by_name['measurement'].fields.append(
  _MEASUREMENTS.fields_by_name['single_int'])
_MEASUREMENTS.fields_by_name['single_int'].containing_oneof = _MEASUREMENTS.oneofs_by_name['measurement']
_MEASUREMENTS.oneofs_by_name['measurement'].fields.append(
  _MEASUREMENTS.fields_by_name['single_double'])
_MEASUREMENTS.fields_by_name['single_double'].containing_oneof = _MEASUREMENTS.oneofs_by_name['measurement']
_MEASUREMENTS.oneofs_by_name['measurement'].fields.append(
  _MEASUREMENTS.fields_by_name['string_values'])
_MEASUREMENTS.fields_by_name['string_values'].containing_oneof = _MEASUREMENTS.oneofs_by_name['measurement']
_MEASUREMENTS.oneofs_by_name['measurement'].fields.append(
  _MEASUREMENTS.fields_by_name['numeric_values'])
_MEASUREMENTS.fields_by_name['numeric_values'].containing_oneof = _MEASUREMENTS.oneofs_by_name['measurement']
_MEASUREMENTS.oneofs_by_name['measurement'].fields.append(
  _MEASUREMENTS.fields_by_name['double_values'])
_MEASUREMENTS.fields_by_name['double_values'].containing_oneof = _MEASUREMENTS.oneofs_by_name['measurement']
_METRIC.fields_by_name['measurements'].message_type = _MEASUREMENTS
_METRIC.fields_by_name['direction'].enum_type = _DIRECTIONALITY
_METRIC.fields_by_name['type'].enum_type = _DATATYPE
DESCRIPTOR.message_types_by_name['Measurements'] = _MEASUREMENTS
DESCRIPTOR.message_types_by_name['StringValues'] = _STRINGVALUES
DESCRIPTOR.message_types_by_name['NumericValues'] = _NUMERICVALUES
DESCRIPTOR.message_types_by_name['DoubleValues'] = _DOUBLEVALUES
DESCRIPTOR.message_types_by_name['Metric'] = _METRIC
DESCRIPTOR.enum_types_by_name['Directionality'] = _DIRECTIONALITY
DESCRIPTOR.enum_types_by_name['DataType'] = _DATATYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Measurements = _reflection.GeneratedProtocolMessageType('Measurements', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENTS,
  '__module__' : 'tools.asuite.atest.tf_proto.metric_measurement_pb2'
  # @@protoc_insertion_point(class_scope:tradefed.metric.Measurements)
  })
_sym_db.RegisterMessage(Measurements)

StringValues = _reflection.GeneratedProtocolMessageType('StringValues', (_message.Message,), {
  'DESCRIPTOR' : _STRINGVALUES,
  '__module__' : 'tools.asuite.atest.tf_proto.metric_measurement_pb2'
  # @@protoc_insertion_point(class_scope:tradefed.metric.StringValues)
  })
_sym_db.RegisterMessage(StringValues)

NumericValues = _reflection.GeneratedProtocolMessageType('NumericValues', (_message.Message,), {
  'DESCRIPTOR' : _NUMERICVALUES,
  '__module__' : 'tools.asuite.atest.tf_proto.metric_measurement_pb2'
  # @@protoc_insertion_point(class_scope:tradefed.metric.NumericValues)
  })
_sym_db.RegisterMessage(NumericValues)

DoubleValues = _reflection.GeneratedProtocolMessageType('DoubleValues', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLEVALUES,
  '__module__' : 'tools.asuite.atest.tf_proto.metric_measurement_pb2'
  # @@protoc_insertion_point(class_scope:tradefed.metric.DoubleValues)
  })
_sym_db.RegisterMessage(DoubleValues)

Metric = _reflection.GeneratedProtocolMessageType('Metric', (_message.Message,), {
  'DESCRIPTOR' : _METRIC,
  '__module__' : 'tools.asuite.atest.tf_proto.metric_measurement_pb2'
  # @@protoc_insertion_point(class_scope:tradefed.metric.Metric)
  })
_sym_db.RegisterMessage(Metric)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
