homepage: "https://sourceforge.net/projects/lame/"
language: c++
primary_contact: "guidovranken@gmail.com"
auto_ccs:
    - "bouvigne@gmail.com"
sanitizers:
 - address
 - memory
architectures:
 - x86_64
 - i386
