#ifndef LOCATION_LBS_CONTEXTHUB_NANOAPPS_UTIL_ARRAY_H_
#define LOCATION_LBS_CONTEXTHUB_NANOAPPS_UTIL_ARRAY_H_

#define ARRAY_SIZE(a) (sizeof((a)) / sizeof((a)[0]))

#endif  // LOCATION_LBS_CONTEXTHUB_NANOAPPS_UTIL_ARRAY_H_
