homepage: "https://github.com/lz4/lz4"
language: c++
primary_contact: "Yann.collet.73@gmail.com"
auto_ccs:
  - "NickRTerrell@gmail.com"
  - "cyan@fb.com"
  - "terrelln@fb.com"
  - "felixh@fb.com"
  - "bimbashrestha@fb.com"
  - "mhl@fb.com"
  - "reed@fb.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - memory
  - undefined
  - dataflow
architectures:
  - x86_64
main_repo: 'https://github.com/lz4/lz4.git'
