homepage: "http://www.libtiff.org"
language: c++
primary_contact: "even.rouault@gmail.com"
auto_ccs:
  - paul.l.kehrer@gmail.com
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
main_repo: 'https://gitlab.com/libtiff/libtiff'
