homepage: "https://github.com/bblanchon/ArduinoJson"
language: c++
primary_contact: "benoit.blanchon@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/bblanchon/ArduinoJson.git'
