homepage: "https://github.com/GrokImageCompression/grok"
primary_contact: "boxerab@gmail.com"
language: c++
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/GrokImageCompression/grok.git'
