homepage: "https://github.com/casync/casync"
language: c++
primary_contact: "lennart@poettering.net"
sanitizers:
  - address
  - undefined
  - memory
auto_ccs:
  - zbyszek@in.waw.pl
  - poettering@gmail.com
  - fsumsal@redhat.com
main_repo: 'https://github.com/systemd/casync'
