homepage: "https://github.com/influxdata/influxdb"
language: go
primary_contact: "william@influxdata.com"
auto_ccs:
  - "palbert@influxdata.com"
  - "ryan@influxdata.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
disabled: true
main_repo: 'https://github.com/influxdata/influxdb'
