homepage: "https://github.com/openthread/wpantund"
language: c++
primary_contact: "rquattle@google.com"
auto_ccs:
 - "abtink@google.com"
 - "wpantund-fuzz@google.com"
main_repo: 'https://github.com/openthread/wpantund'
