homepage: "https://github.com/radare/radare2"
language: c++
primary_contact: "pancake@nopcode.org"
auto_ccs:
  - "zlowram@gmail.com"
sanitizers:
  - address
run_tests: False
main_repo: 'https://github.com/radare/radare2'
