homepage: "https://github.com/tytso/e2fsprogs"
language: c
primary_contact: "tytso@mit.edu"
auto_ccs:
  - "theodore.tso@gmail.com"
  - "tytso@google.com"
main_repo: 'https://github.com/tytso/e2fsprogs'
