homepage: "https://www.gnu.org/software/binutils/"
language: c++
primary_contact: "bug-binutils@gnu.org"
auto_ccs :
  - "p.antoine@catenacyber.fr"
  - "nickc@redhat.com"
  - "amodra@gmail.com"
  - "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - undefined
  - memory
  - dataflow
