{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-common",
    "version": "3.0.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-3.0.0-beta01.jar",
          "url": "paging-common-3.0.0-beta01.jar",
          "size": 756097,
          "sha512": "f61abb2a11a4306e62feb323dc74276c3a47ca134fc9612eec9de55c1bcb1083bcea5b6253c73c9a078048f7f3207e320b5b29dc8ba8eb25b3c63ae9d93d4533",
          "sha256": "34450b3bcb41e5a230c1b45a283caca293d3e72e25f9f70f7bbf8597ff671a78",
          "sha1": "d1e57e8b37a0d05f707ae7f264886489c6d76c7c",
          "md5": "6ab085b8bcd96a15c007c46caa66f8eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-3.0.0-beta01.jar",
          "url": "paging-common-3.0.0-beta01.jar",
          "size": 756097,
          "sha512": "f61abb2a11a4306e62feb323dc74276c3a47ca134fc9612eec9de55c1bcb1083bcea5b6253c73c9a078048f7f3207e320b5b29dc8ba8eb25b3c63ae9d93d4533",
          "sha256": "34450b3bcb41e5a230c1b45a283caca293d3e72e25f9f70f7bbf8597ff671a78",
          "sha1": "d1e57e8b37a0d05f707ae7f264886489c6d76c7c",
          "md5": "6ab085b8bcd96a15c007c46caa66f8eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-common-3.0.0-beta01-sources.jar",
          "url": "paging-common-3.0.0-beta01-sources.jar",
          "size": 138299,
          "sha512": "8eb88979a9350cf2772cea2d0c13e89f036691af2dd0f4d216107df8d979733b4a1913d1583db0fefec61ea93e4771933694e76405e5e7c549c7f678d68ed1bf",
          "sha256": "c1ed0919b01fece1bc22ebcecde82d8b58532ecdd7d88516aec610240b16de69",
          "sha1": "fb7aea27a3b7932fb3a138cf46fbc72c81bef45b",
          "md5": "cb9a233157b1b019c503709cb92c041a"
        }
      ]
    }
  ]
}
