homepage: "http://www.wavpack.com" 
language: c++
primary_contact: "david@wavpack.com" 
auto_ccs:
- dvbryant@gmail.com
- thuanpv.nus@gmail.com
sanitizers: 
- address 
- memory
- undefined
main_repo: 'https://github.com/dbry/WavPack.git'
