{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-1.4.0-alpha01.aar",
          "url": "fragment-1.4.0-alpha01.aar",
          "size": 306260,
          "sha512": "0bf3e1f2efbf47bff192001828333c49795dda49d2bd95e2c44873c15d137f0e1b9ded28e0fdf02cc92df92942b0eed43e99b7e2f045f7ad826c4838dedfece9",
          "sha256": "e7a6b81113b76afae8d9915992e7b07f4be97650d952a589a2b4aa3ab60d215c",
          "sha1": "fae1ac3a9c6afd0dfd26ec8eef54b248adc56207",
          "md5": "7e3ea2f7eca29235f587a5e810096013"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-1.4.0-alpha01.aar",
          "url": "fragment-1.4.0-alpha01.aar",
          "size": 306260,
          "sha512": "0bf3e1f2efbf47bff192001828333c49795dda49d2bd95e2c44873c15d137f0e1b9ded28e0fdf02cc92df92942b0eed43e99b7e2f045f7ad826c4838dedfece9",
          "sha256": "e7a6b81113b76afae8d9915992e7b07f4be97650d952a589a2b4aa3ab60d215c",
          "sha1": "fae1ac3a9c6afd0dfd26ec8eef54b248adc56207",
          "md5": "7e3ea2f7eca29235f587a5e810096013"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-1.4.0-alpha01-sources.jar",
          "url": "fragment-1.4.0-alpha01-sources.jar",
          "size": 189811,
          "sha512": "c5376086d32ef660ba25edc852c5fe2fa77ee46a19da5734e81bf892bf7565a165d29e0f6380f6570e9e4ce3dc9635fc69af929cf85e7c34e80cf299dc30436d",
          "sha256": "a5dad2263d4fad067bbd8d2d49656d1809537bd443f7db53a2f6897d06c7582b",
          "sha1": "7c8af56e429c0ef7349a9421ca765a2562cc17ac",
          "md5": "344a40c69457b632e63926fab1234cc5"
        }
      ]
    }
  ]
}
