homepage: "https://github.com/nmoinvaz/minizip"
language: c++
primary_contact: "nathan.moinvaziri@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/nmoinvaz/minizip'
