homepage: "https://solidity.readthedocs.io"
language: c++
primary_contact: "bhargava.shastry@ethereum.org"
auto_ccs:
  - "axic@ethereum.org"
  - "christian@ethereum.org"
  - "martin.swende@ethereum.org"
main_repo: 'https://github.com/ethereum/solidity.git'
