{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-1.2.0-alpha01.aar",
          "url": "savedstate-1.2.0-alpha01.aar",
          "size": 11307,
          "sha512": "9e775c0466829351c17cbf37aabf73083326dcdd6636a92257a7046a558b35fa880838fb0f8814f50c27ab3d27216173090dd2d22c2739e2e45ee3aebb75a91f",
          "sha256": "5a0d086374708016c89b21a23f62b7990f32af2ff1e30945743b18b985ec4e1d",
          "sha1": "33dee40c1a9ec9f18d04bad951b112559c9b5cf2",
          "md5": "ac03780061239b6fc3a379aa8fb8655d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-1.2.0-alpha01.aar",
          "url": "savedstate-1.2.0-alpha01.aar",
          "size": 11307,
          "sha512": "9e775c0466829351c17cbf37aabf73083326dcdd6636a92257a7046a558b35fa880838fb0f8814f50c27ab3d27216173090dd2d22c2739e2e45ee3aebb75a91f",
          "sha256": "5a0d086374708016c89b21a23f62b7990f32af2ff1e30945743b18b985ec4e1d",
          "sha1": "33dee40c1a9ec9f18d04bad951b112559c9b5cf2",
          "md5": "ac03780061239b6fc3a379aa8fb8655d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "savedstate-1.2.0-alpha01-sources.jar",
          "url": "savedstate-1.2.0-alpha01-sources.jar",
          "size": 8564,
          "sha512": "6f3a05df6886aae59fdbd8ad4bb4c207419cee97401a848726c7698d038c123cf39b8f15bfd1eef7ba5ed3ea0c16b200b305b5ba6106cf957cf77405cc2f4985",
          "sha256": "17a5307db49192c506456ece77352c58c621ec35a280ebad3ecbe2d5dd586df3",
          "sha1": "073464c2c55129727354a95ffa91dc9c2cf0c78b",
          "md5": "fc3f8c39a1ebe510256d9e62669e9774"
        }
      ]
    }
  ]
}
