homepage: "https://github.com/GNUAspell/aspell"
language: c++
primary_contact: "kevina@gnu.org"
auto_ccs:
  - "kevinatkn@gmail.com"
  - "cmeister2@gmail.com"
sanitizers:
  - address
  - undefined
  - memory:
      experimental: true
main_repo: 'https://github.com/gnuaspell/aspell.git'
