[package]
name = "zipfuse"
version = "0.1.0"
authors = ["Jiyong Park <jiyong@google.com>"]
edition = "2018"

[dependencies]
fuse = { path = "../../../../external/crosvm/fuse" }
clap = "2.33"
anyhow = "1.0"
libc = "0.2"
zip = "0.5"
tempfile = "3.2"
nix = "0.20"
