homepage: "http://qt-project.org"
language: c++
primary_contact: "rlohningqt@gmail.com"
auto_ccs:
 - "shawn.t.rutledge@gmail.com"
architectures:
 - x86_64
 - i386
main_repo: 'git://code.qt.io/qt/qt5.git'
