{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.0-alpha03.aar",
          "url": "activity-ktx-1.3.0-alpha03.aar",
          "size": 20372,
          "sha512": "96eb8768d28efc848e3df0393257c9f68c2862cdc9695f97d9d5cd559b84e6bdd600c504e32410bc02e6f93bb1f187d2725c2aec25f2186e8541646b18bb6821",
          "sha256": "4a91e267a33159afc2197b2fbe7a14746e5cc31bae9420936ee0865c731168ee",
          "sha1": "369cf22174f07051044341b471d54d51fb29df19",
          "md5": "ee4dff7aed23b0e577f8eaf2f3f4737c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.3.0-alpha03.aar",
          "url": "activity-ktx-1.3.0-alpha03.aar",
          "size": 20372,
          "sha512": "96eb8768d28efc848e3df0393257c9f68c2862cdc9695f97d9d5cd559b84e6bdd600c504e32410bc02e6f93bb1f187d2725c2aec25f2186e8541646b18bb6821",
          "sha256": "4a91e267a33159afc2197b2fbe7a14746e5cc31bae9420936ee0865c731168ee",
          "sha1": "369cf22174f07051044341b471d54d51fb29df19",
          "md5": "ee4dff7aed23b0e577f8eaf2f3f4737c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.3.0-alpha03-sources.jar",
          "url": "activity-ktx-1.3.0-alpha03-sources.jar",
          "size": 6129,
          "sha512": "c200adb95b52aa1e21baa37cc4a09ba40c7953e5b9d976af27d341358120aa6fcff35820566e852c698600379ff4421927b7defe72b39664709c6cf1ff1c9bb6",
          "sha256": "efaf9cabd37472c01a222864f955218fb43dfe1a8f0ceddf7bf99bae11000af3",
          "sha1": "827664f9421e56e79f9eed7223ba4a5d67d941c2",
          "md5": "df582cf41df416363a854f5a5cede6ca"
        }
      ]
    }
  ]
}
