homepage: "https://github.com/gohugoio/hugo"
primary_contact: "bjorn.erik.pedersen@gmail.com"
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: 'https://github.com/gohugoio/hugo'
