sudo: required
language: c
services:
- docker
compiler:
- gcc
- clang
env:
  matrix:
   # ubuntu 16.04
  - DOCKER_TAG=ubuntu-16.04
   # ubuntu 18.04
  - DOCKER_TAG=ubuntu-18.04
    # fedora-30
  - DOCKER_TAG=fedora-30
   # opensuse-leap
  - DOCKER_TAG=opensuse-leap

  global:
  # COVERITY_SCAN_TOKEN
  - secure: "ZD0KxBhO/CaSE/TOkW+H5nsBbaMolbIPv5DgctcjA1BlTckgc5lK4m+7BIR1Fft6gaeeLOoCY3qUm4kW++Bqk2bTsrx/HvrmVmrzMO572jA74x4E+5lynUnRVaAgBg7cVBcB0hZcUurx8FifNBbgnWlxT/nDWttVnglkz400GCE9/zy+VTJWqt4QAB+6qeKPiG3vRthQdWcHstBI8IIAbvp4rhSUajBBQeZ5ro5RPGNy+iHen+t6tyJmbjiP0Y4qjkKGbfwXHnsseEcuSJQuxSkQ9MWK6t93BFXFSPw5MjHIApMn+4CjRp2JMoVTVfe5fFeZEHxVUmAzy+e5eIeftrUtUlCI293UuxZnw/vpJczn3BWunlhhjqjsCwVeknzGHxlaT+ck8Et1Mdl/3nY/E9dt47/NOzXY2xrAz59GYsdKvvsPoCGgNlAub03Vl0W24I1kjppsmN/zFwazHGqoxIBTwrDOQUmZvPfXA3jAUozrfAdT3YjnRcCG7bbQmacFApqfUm/bqMgapAgozjjxpuBrO1wQSUjjH6NANZsP2Gpk0eAl7FOlBzbVgKPxCQozWCjpKOj3HMnXX458ZQWsboG5J00wwjw9DRNRCkeexLdi832L/BPhUY5JgRlTqqyKr9cr69DvogBF/pLytpSCciF6t9NqqGZYbBomXJLaG84="
  # run coverity scan on gcc build to keep from DOSing coverity
  - coverity_scan_run_condition='"$CC" = gcc'

matrix:
  include:
  # gcrypt testing
  - env: DOCKER_TAG=fedora-30 WITH_CRYPTO=gcrypt
    compiler: gcc
  - env: DOCKER_TAG=opensuse-leap WITH_CRYPTO=gcrypt
    compiler: clang
  - env: DOCKER_TAG=ubuntu-16.04 WITH_CRYPTO=gcrypt
    compiler: gcc
  - env: DOCKER_TAG=ubuntu-18.04 WITH_CRYPTO=gcrypt
    compiler: clang
  # tcti async and partial read testing
  - env: DOCKER_TAG=fedora-30 WITH_TCTI_ASYNC=yes WITH_TCTI_PARTIAL=yes WITH_CRYPTO=gcrypt
    compiler: gcc
  - env: DOCKER_TAG=fedora-30 WITH_TCTI_ASYNC=yes WITH_TCTI_PARTIAL=no
    compiler: gcc
  - env: DOCKER_TAG=fedora-30 WITH_TCTI_ASYNC=no WITH_TCTI_PARTIAL=yes
    compiler: gcc
  # coverage check
  - env: DOCKER_TAG=ubuntu-18.04 ENABLE_COVERAGE=true
    compiler: gcc
  # scan build check
  - env: DOCKER_TAG=fedora-30 SCANBUILD=yes WITH_TCTI_ASYNC=yes WITH_TCTI_PARTIAL=yes
    compiler: clang
  # check fuzz targets
  - env: DOCKER_TAG=fedora-30 GEN_FUZZ=1 CXX=clang++ CC=clang
    compiler: clang

script:
  - ./.ci/travis.run

after_failure:
  - cat build/test-suite.log
