{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recyclerview",
    "module": "recyclerview",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.3.0-alpha01.aar",
          "url": "recyclerview-1.3.0-alpha01.aar",
          "size": 405141,
          "sha512": "7b9289f2a674b17c16a1b123e3b34d67ba0b1e4272413239f6d3bc9e7962afcdbe06086eb27fefa94f5da47db3d8b4151d48f3c195c66f6799e59b1be54ae6bb",
          "sha256": "1622bf9afc55ac058dea3f4a82f46e75365ca84a4c363df0ae843066cd7d4045",
          "sha1": "10845c140c9bd86d7e30c7dd5b39f62127ce3d69",
          "md5": "a7952b35316f656a0918f50319f9d516"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.3.0-alpha01.aar",
          "url": "recyclerview-1.3.0-alpha01.aar",
          "size": 405141,
          "sha512": "7b9289f2a674b17c16a1b123e3b34d67ba0b1e4272413239f6d3bc9e7962afcdbe06086eb27fefa94f5da47db3d8b4151d48f3c195c66f6799e59b1be54ae6bb",
          "sha256": "1622bf9afc55ac058dea3f4a82f46e75365ca84a4c363df0ae843066cd7d4045",
          "sha1": "10845c140c9bd86d7e30c7dd5b39f62127ce3d69",
          "md5": "a7952b35316f656a0918f50319f9d516"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recyclerview-1.3.0-alpha01-sources.jar",
          "url": "recyclerview-1.3.0-alpha01-sources.jar",
          "size": 322308,
          "sha512": "64561ec6d8a6b97ca2a177302c86423dd93128038a3c5ba0271e6319fd024e17de525ab9cb4d7ff16a667baf8ab8d5365dfe2520e210e851bd0c63044e1db6d1",
          "sha256": "2b8c32871d60622dff31ee7231017b122f397af7be046de129f648ba2814dac1",
          "sha1": "735ea273c313081a5b9c78901ba5546ae94ca6ba",
          "md5": "8586197ef4a7811fa1a2e1d5f9bbdd64"
        }
      ]
    }
  ]
}
