[package]
name = "hypervisor"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
bit_field = { path = "../bit_field" }
data_model = { path = "../data_model" }
downcast-rs = "1.2.0"
enumn = { path = "../enumn" }
kvm = { path = "../kvm" }
kvm_sys = { path = "../kvm_sys" }
libc = "*"
serde = { version = "1", features = [ "derive" ] }
sync = { path = "../sync" }
base = { path = "../base" }
vm_memory = { path = "../vm_memory" }
