homepage: "https://bearssl.org/"
language: c++
primary_contact: "guidovranken@gmail.com"
auto_ccs:
    - "pornin@gmail.com"
sanitizers:
 - address
 - undefined
 - memory
architectures:
 - x86_64
 - i386
