{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.versionedparcelable",
    "module": "versionedparcelable",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "versionedparcelable-1.2.0-alpha01.aar",
          "url": "versionedparcelable-1.2.0-alpha01.aar",
          "size": 31705,
          "sha512": "200b75ee2bb9d8c46b8efe38ba660a4e832507e67023c21c25a584fa494860e9d806d95631bd5bf0d22c0ba17e7a8c358473d26fda72dd1a800ee4be8ab3e3c2",
          "sha256": "e1c7568f67558a06ed2a705bfbcf56d45f455e020463ad66229de8b2635d28a3",
          "sha1": "ff34edae09b51bd9b4c0374ec62630e4ba6135f7",
          "md5": "2ed3cab621029703bfde47d200f1194e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "versionedparcelable-1.2.0-alpha01.aar",
          "url": "versionedparcelable-1.2.0-alpha01.aar",
          "size": 31705,
          "sha512": "200b75ee2bb9d8c46b8efe38ba660a4e832507e67023c21c25a584fa494860e9d806d95631bd5bf0d22c0ba17e7a8c358473d26fda72dd1a800ee4be8ab3e3c2",
          "sha256": "e1c7568f67558a06ed2a705bfbcf56d45f455e020463ad66229de8b2635d28a3",
          "sha1": "ff34edae09b51bd9b4c0374ec62630e4ba6135f7",
          "md5": "2ed3cab621029703bfde47d200f1194e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versionedparcelable-1.2.0-alpha01-sources.jar",
          "url": "versionedparcelable-1.2.0-alpha01-sources.jar",
          "size": 21173,
          "sha512": "5a094e4df41b34eb2257b28d902acebd3cd5b191978f29dfc974116c2a68eb27e6f03360ea19a1411bfeb5d3684c7895951da9a8083ef6f70157177f09423712",
          "sha256": "562c0ac7f0c03798d5648a531d9227044e1bbd1a7a786f3740fdc79806c85ac7",
          "sha1": "1fddbabedeb0ff43f5e3506fe8b67d67e143f950",
          "md5": "7009c75f5d8fc09a971a5e444db1ebc7"
        }
      ]
    }
  ]
}
