{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.autofill",
    "module": "autofill",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "autofill-1.2.0-alpha01.aar",
          "url": "autofill-1.2.0-alpha01.aar",
          "size": 36936,
          "sha512": "aed3fcf229cf02715a299763f918ae95c845a6e987e506ece1eb1b487574f98eaaed288e0cc2966af21d3da04dc94ff66d22fb18577945c66f6de4e89e6866fa",
          "sha256": "b4bdcd855f43965f7d0c84a1a6da54c91797d7acd2a5404cc1aa0f872e5899cc",
          "sha1": "60b95067c7aa0ac1e13c70ca0ed0e38e4eaa2cd2",
          "md5": "9888a13032bba046607709cffcddea45"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "autofill-1.2.0-alpha01.aar",
          "url": "autofill-1.2.0-alpha01.aar",
          "size": 36936,
          "sha512": "aed3fcf229cf02715a299763f918ae95c845a6e987e506ece1eb1b487574f98eaaed288e0cc2966af21d3da04dc94ff66d22fb18577945c66f6de4e89e6866fa",
          "sha256": "b4bdcd855f43965f7d0c84a1a6da54c91797d7acd2a5404cc1aa0f872e5899cc",
          "sha1": "60b95067c7aa0ac1e13c70ca0ed0e38e4eaa2cd2",
          "md5": "9888a13032bba046607709cffcddea45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "autofill-1.2.0-alpha01-sources.jar",
          "url": "autofill-1.2.0-alpha01-sources.jar",
          "size": 25672,
          "sha512": "d3e8e86656c9b14e4a1ae10e5667f4334f4e7955fc3f308b28fa3e04745be0d1e7c2a9707e888009c42652ddc4f7427c1d993d164a7d35d749602bd3228964f2",
          "sha256": "e154868bda2328908a4674998af3a09e3f65a649d95a87cbfe3f1aa415e28f2b",
          "sha1": "078bdbf14bb97d579bf191bc0de7e969027c4375",
          "md5": "25dd0e229cae0f7da23bddf7c9423e91"
        }
      ]
    }
  ]
}
