homepage: "https://github.com/google/draco"
language: c++
primary_contact: "fgalligan@google.com"
auto_ccs:
  - "ostava@google.com"
  - "vytyaz@google.com"
main_repo: 'https://github.com/google/draco'
