homepage: "http://www.darwinsys.com/file/"
language: c++
primary_contact: "zoulasc@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/file/file.git'
