homepage: https://poppler.freedesktop.org/
language: c++
primary_contact: tsdgeos@gmail.com
sanitizers:
  - address
  - memory
  - undefined
auto_ccs:
  - jonathan@titanous.com
  - adam.reichold@t-online.de
main_repo: 'https://anongit.freedesktop.org/git/poppler/poppler.git'
