homepage: "https://github.com/google/jsonnet"
language: c++
primary_contact: "dcunnin@google.com"
auto_ccs:
  - "wwweiwang@google.com"
  - "sparkprime@gmail.com"

sanitizers:
  - address
  - memory
  - undefined

labels:
  convert_jsonnet_fuzzer:
    - sundew

architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/google/jsonnet.git'
