homepage: "https://github.com/WebAssembly/wabt"
language: c++
primary_contact: "binji@chromium.org"
sanitizers:
 - address
 - memory
 - undefined
architectures:
 - x86_64
 - i386
main_repo: 'https://github.com/WebAssembly/wabt'
