homepage: "https://git-scm.com"
language: c++
primary_contact: "steadmon@google.com"
auto_ccs:
  - "git-fuzz-reports@google.com"
  - "emilyshaffer@google.com"
  - "jonathantanmy@google.com"
  - "jrn@google.com"
main_repo: 'https://github.com/git/git'
