homepage: "https://www.envoyproxy.io/"
language: c++
primary_contact: "htuch@google.com"
auto_ccs:
  - "mattklein123@gmail.com"
  - "alyssar@google.com"
  - "dio@tetrate.io"
  - "jmarantz@google.com"
  - "lizan@tetrate.io"
  - "envoy-security@googlegroups.com"
  - "yavlasov@google.com"
  - "asraa@google.com"
  - "adip@google.com"
  - "avd@google.com"
  - "skerner@google.com"
  - "rdsmith@google.com"
  - "chaoqinli@google.com"
  - "yanjunxiang@google.com"
  - "arquebus@appspot.gserviceaccount.com"
  - "david@adalogics.com"
coverage_extra_args: -ignore-filename-regex=.*\.cache.*envoy_deps_cache.*
main_repo: 'https://github.com/envoyproxy/envoy.git'
