{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tracing-1.1.0-alpha01.aar",
          "url": "tracing-1.1.0-alpha01.aar",
          "size": 5094,
          "sha512": "aa8c530f36d8350018e482ee865f151c588848a27e363099bc6e02c24358723e1628ccc2bef0597ed969be4f374a733a505281d267b7ec27526efa4c9543659f",
          "sha256": "25f51ddba7d387838d161292113ac032ebc669cea6f1efa3d23e5ca846747d46",
          "sha1": "3de9ba9cf0a472bd1069ea4f8848903c1957c063",
          "md5": "c62de2ae9a3b0db58779fab37ffa2093"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-1.1.0-alpha01.aar",
          "url": "tracing-1.1.0-alpha01.aar",
          "size": 5094,
          "sha512": "aa8c530f36d8350018e482ee865f151c588848a27e363099bc6e02c24358723e1628ccc2bef0597ed969be4f374a733a505281d267b7ec27526efa4c9543659f",
          "sha256": "25f51ddba7d387838d161292113ac032ebc669cea6f1efa3d23e5ca846747d46",
          "sha1": "3de9ba9cf0a472bd1069ea4f8848903c1957c063",
          "md5": "c62de2ae9a3b0db58779fab37ffa2093"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracing-1.1.0-alpha01-sources.jar",
          "url": "tracing-1.1.0-alpha01-sources.jar",
          "size": 5581,
          "sha512": "38637c78f62d2591f6f965df88a5a3b5eeddf079ec82020eabf8baae1af0e706828ab81d8a368a2ff8d77744e73b010d0297c4e70da530f3ecf456d6664032c7",
          "sha256": "a593c115d145df9cb9ae2226960da1d53ff8590eff1c285e7c9de2b6727d3c21",
          "sha1": "aa6dafdce323d80a993c5427cf81d5072f023c8c",
          "md5": "a54304b44519d7d24390d3d6f34918ba"
        }
      ]
    }
  ]
}
