homepage: "https://www.ntop.org/products/deep-packet-inspection/ndpi/"
language: c++
primary_contact: "luca.deri@gmail.com"
auto_ccs :
  - "p.antoine@catenacyber.fr"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - undefined
  - memory
main_repo: 'https://github.com/ntop/nDPI.git'
