homepage: "https://hunspell.github.io/"
language: c++
primary_contact: "caolanm@redhat.com"
auto_ccs:
  - "security@documentfoundation.org"
vendor_ccs:
  - "ehsan.akhgari@gmail.com"
  - "twsmith@mozilla.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
 - i386
 - x86_64
main_repo: 'https://github.com/hunspell/hunspell.git'
