{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.percentlayout",
    "module": "percentlayout",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "percentlayout-1.1.0-alpha01.aar",
          "url": "percentlayout-1.1.0-alpha01.aar",
          "size": 14081,
          "sha512": "5516beb18810d73f6e8d3633384038db9dc6acf7f4b9e0b11ff18d2bfb4048499c625431b7266200365f6165acb121444c41345a89200d1168b08ede57e9ac04",
          "sha256": "dea1b3e055972da3af1704628e540e74a82787255ed762ee4fa9180e061388f7",
          "sha1": "0971aaa2fa50a6c57b061802a15cf9a6af325ee1",
          "md5": "6380f3a1302b79bedd95f6e9f871b8b2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "percentlayout-1.1.0-alpha01.aar",
          "url": "percentlayout-1.1.0-alpha01.aar",
          "size": 14081,
          "sha512": "5516beb18810d73f6e8d3633384038db9dc6acf7f4b9e0b11ff18d2bfb4048499c625431b7266200365f6165acb121444c41345a89200d1168b08ede57e9ac04",
          "sha256": "dea1b3e055972da3af1704628e540e74a82787255ed762ee4fa9180e061388f7",
          "sha1": "0971aaa2fa50a6c57b061802a15cf9a6af325ee1",
          "md5": "6380f3a1302b79bedd95f6e9f871b8b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "percentlayout-1.1.0-alpha01-sources.jar",
          "url": "percentlayout-1.1.0-alpha01-sources.jar",
          "size": 11165,
          "sha512": "a59b5f34e6f8751dcf94794f4de6732e6d135e088becb3eba434ae5a455638e57e78397df5d03480856841341463e7158eb39e650c92041c033d73cd2df72ebf",
          "sha256": "f8486765b1409524ebe594edcc9cecd264fcfa377107b96c599a3128721f2838",
          "sha1": "a10000cdcd18b9a187b90af6d6b9e928eb850f9b",
          "md5": "b3ecd976c129924707634b4016c4f594"
        }
      ]
    }
  ]
}
