{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler",
    "version": "2.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7164647"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "room-compiler-2.3.0-beta02.jar",
          "url": "room-compiler-2.3.0-beta02.jar",
          "size": 3596316,
          "sha512": "c5445a862f1d9011894316f87f0da9063f1aecae527c6dc9c6ab4571965f88f837268750057fe0fa2e479ad11f82ff0d046bdf81691b2d0dad5d2c9c456ecb3a",
          "sha256": "1872c9d0c53fee34d78b38a7c383f4e8f436bf8f721adb52d257d82042019d59",
          "sha1": "b39bc7cd8b6bedf146a33bdd988cc91d0b93f33f",
          "md5": "7fe0e6ae6c19fe5b5131f35cfe2dfc5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0-beta02"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.3.0-beta02"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.3.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.4.30-1.0.0-alpha02"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.25.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.3.0-beta02.jar",
          "url": "room-compiler-2.3.0-beta02.jar",
          "size": 3596316,
          "sha512": "c5445a862f1d9011894316f87f0da9063f1aecae527c6dc9c6ab4571965f88f837268750057fe0fa2e479ad11f82ff0d046bdf81691b2d0dad5d2c9c456ecb3a",
          "sha256": "1872c9d0c53fee34d78b38a7c383f4e8f436bf8f721adb52d257d82042019d59",
          "sha1": "b39bc7cd8b6bedf146a33bdd988cc91d0b93f33f",
          "md5": "7fe0e6ae6c19fe5b5131f35cfe2dfc5e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-2.3.0-beta02-sources.jar",
          "url": "room-compiler-2.3.0-beta02-sources.jar",
          "size": 404913,
          "sha512": "4fe1345eb5e0950481238b0cafd71a37bfcc2982dac70ef1f87950d604c897fc352b648ee3f8f3876836f61a706d3550eda237c154d3e96a6141b3488f9d7f29",
          "sha256": "731d04c6890316d6514ce586be23e4e1de94f617939fba7351e05d369843d46d",
          "sha1": "e87f1833cd16c8fd67f6c04476b74eb43552c7e9",
          "md5": "bccd80b8251e7d1a8ce2cf07e3c20174"
        }
      ]
    }
  ]
}
