homepage: "https://github.com/libevent/libevent"
language: c++
primary_contact: "a3at.mail@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/libevent/libevent.git'
