language: rust
rust:
  - stable
  - beta
  - nightly
# Oldest supported version:
  - 1.32.0

dist: trusty
sudo: false

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never

addons:
  apt:
    packages:
      - texinfo
